---
name: Code Review (Full)

##########################################
# Start the job on pull requests to main #
##########################################
on:
  pull_request:
    branches: [master]

###############
# Set the Job #
###############
jobs:

  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      # Release tag v3.3.0 onwards includes arm-ttk linter
      uses: docker://github/super-linter:v3.3.2
      env:
        # Lint all code on pull_request
        VALIDATE_ALL_CODEBASE: true
        # Need to define main branch as default is master
        DEFAULT_BRANCH: master
